## Data Preprocessing Tools

Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pls

Importing the dataset

In [2]:
dataset = pd.read_csv("Data.csv")
# Xler bizim feature vektörümüz olurken y bizim dependent veriablemiz olacak
# dataset.iloc[:,:] ilk : alınacak row sayısını ifade ederken ikinci : alınacak column sayısını ifade eder
# Burada bütün verileri almak isteyip sadece verilerimizi columna göre bölmek istediğimiz için ilk : olduğu gibi bırakıyoruz
# : olduğu gibi bırakmak demek hepsini al demektir.
# .values eki sadece verileri al demek yani column nameleri ve row indexleri aradan çıkarılır.
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
missing_values = dataset.isna().sum()

In [7]:
print(missing_values)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


Taking care of missing data

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

In [9]:
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [18]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding categorical data

Encoding the Independent Variable

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [21]:
# transformers argümanı içerisinde 3 değer olan bir tuple alacaktır
# [('transformerimize vermek istediğimiz isim (herhangi bir şey olabilir)'),Kullanacağımız encoder vey columntransformer,[uygulanacağı index]]
# remainder = 'passthrough' olarak bırakılmasının sebebi dönüşüm yapılmayacak sütünların olduğu gibi kalmasını sağlamaktır.
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])], remainder = 'passthrough')
# fit_transform kodu ayarladığımız dönüşümleri istediğimiz veri setine uygular ve işlenmiş veri setini döndürür
# yanlız veri setinin geri dönüş tipi np arrayi olmadığından outputu np.array() içine alarak np arrayi olmaya zorlarız.
X = np.array(ct.fit_transform(X))

In [22]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the Dependent Variable

In [24]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [33]:
# Yukarıda da görüldüğü üzere y verisetimiz matris değil vektör şeklindedir.
# Bu yüzden y verisetimizi label olarak tanımlarız
# Labelleri encode etmek için başka bir fonksiyon kullanırız
# Ayrıca bu şekilde kullanabilmemizin sebebi sadece 2 classa sahip olmasıdır
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()
y = le.fit_transform(y)

In [32]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the Training set and Test set