In [152]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [153]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [154]:
print(X[10])

[101913.08 110594.11 229160.95 'Florida']


In [155]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


Kategorik verileri encode etme (OneHot yöntemi ile)

In [156]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [157]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder = 'passthrough')

In [158]:
X = np.array(ct.fit_transform(X))

In [159]:
print(X[10])

[0.0 1.0 0.0 101913.08 110594.11 229160.95]


Dummy Variable tuzağından kurtulma

In [160]:
X = X[:,1:]

In [161]:
from sklearn.model_selection import train_test_split

In [162]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [163]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [164]:
y_pred_without_backward_elimination = regressor.predict(X_test)

In [165]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_without_backward_elimination.reshape(len(y_pred_without_backward_elimination),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [166]:
print(y_pred)

[103015.2  132582.28 132447.74  71976.1  178537.48 116161.24  67851.69
  98791.73 113969.44 167921.07]


Backward Eliminarion Yöntemi İle Optimal Feature Tablosunu bulma

Backward Elimination Yöntemi P > SL için feature'i feature tablosundan çıkararak ilerleyen iteratif bir yöntemdir
Her seferinde 1 P > SL (SL = 0.05) olan bir feature feature tablosundan çıkarılır ve bütün model tekrardan eğitilir.
Model eğitimi sonucunda verilere tekrardan bakılır ve sonucuda hala P > SL varsa o feature çıkarılıp model tekrardan eğitilir
Tablonunun içinde P > SL verisine sahip olan feature kalmayana kadar devam edilir
Bu featureler temizlendikten sonra optimum feature tablosuna ulaşılmış kabul edilir.
P > SL sıralaması için seçim şeklide en yüksek p'ye sahip olan en önce çıkarılır.

In [167]:
import statsmodels.api as sm

In [168]:
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1)

In [169]:
print(X)

[[1 0.0 1.0 165349.2 136897.8 471784.1]
 [1 0.0 0.0 162597.7 151377.59 443898.53]
 [1 1.0 0.0 153441.51 101145.55 407934.54]
 [1 0.0 1.0 144372.41 118671.85 383199.62]
 [1 1.0 0.0 142107.34 91391.77 366168.42]
 [1 0.0 1.0 131876.9 99814.71 362861.36]
 [1 0.0 0.0 134615.46 147198.87 127716.82]
 [1 1.0 0.0 130298.13 145530.06 323876.68]
 [1 0.0 1.0 120542.52 148718.95 311613.29]
 [1 0.0 0.0 123334.88 108679.17 304981.62]
 [1 1.0 0.0 101913.08 110594.11 229160.95]
 [1 0.0 0.0 100671.96 91790.61 249744.55]
 [1 1.0 0.0 93863.75 127320.38 249839.44]
 [1 0.0 0.0 91992.39 135495.07 252664.93]
 [1 1.0 0.0 119943.24 156547.42 256512.92]
 [1 0.0 1.0 114523.61 122616.84 261776.23]
 [1 0.0 0.0 78013.11 121597.55 264346.06]
 [1 0.0 1.0 94657.16 145077.58 282574.31]
 [1 1.0 0.0 91749.16 114175.79 294919.57]
 [1 0.0 1.0 86419.7 153514.11 0.0]
 [1 0.0 0.0 76253.86 113867.3 298664.47]
 [1 0.0 1.0 78389.47 153773.43 299737.29]
 [1 1.0 0.0 73994.56 122782.75 303319.26]
 [1 1.0 0.0 67532.53 105751.03 30476

In [171]:
X_opt = X[:,[0,1,2,4,5]]
X_opt = X_opt.astype(np.float64)

In [172]:
print(X_opt)

[[1.00e+00 0.00e+00 1.00e+00 1.37e+05 4.72e+05]
 [1.00e+00 0.00e+00 0.00e+00 1.51e+05 4.44e+05]
 [1.00e+00 1.00e+00 0.00e+00 1.01e+05 4.08e+05]
 [1.00e+00 0.00e+00 1.00e+00 1.19e+05 3.83e+05]
 [1.00e+00 1.00e+00 0.00e+00 9.14e+04 3.66e+05]
 [1.00e+00 0.00e+00 1.00e+00 9.98e+04 3.63e+05]
 [1.00e+00 0.00e+00 0.00e+00 1.47e+05 1.28e+05]
 [1.00e+00 1.00e+00 0.00e+00 1.46e+05 3.24e+05]
 [1.00e+00 0.00e+00 1.00e+00 1.49e+05 3.12e+05]
 [1.00e+00 0.00e+00 0.00e+00 1.09e+05 3.05e+05]
 [1.00e+00 1.00e+00 0.00e+00 1.11e+05 2.29e+05]
 [1.00e+00 0.00e+00 0.00e+00 9.18e+04 2.50e+05]
 [1.00e+00 1.00e+00 0.00e+00 1.27e+05 2.50e+05]
 [1.00e+00 0.00e+00 0.00e+00 1.35e+05 2.53e+05]
 [1.00e+00 1.00e+00 0.00e+00 1.57e+05 2.57e+05]
 [1.00e+00 0.00e+00 1.00e+00 1.23e+05 2.62e+05]
 [1.00e+00 0.00e+00 0.00e+00 1.22e+05 2.64e+05]
 [1.00e+00 0.00e+00 1.00e+00 1.45e+05 2.83e+05]
 [1.00e+00 1.00e+00 0.00e+00 1.14e+05 2.95e+05]
 [1.00e+00 0.00e+00 1.00e+00 1.54e+05 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00 1.14e+05 2.

In [173]:
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()

In [174]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.613
Model:                            OLS   Adj. R-squared:                  0.579
Method:                 Least Squares   F-statistic:                     17.83
Date:                Tue, 24 Oct 2023   Prob (F-statistic):           7.78e-09
Time:                        22:01:23   Log-Likelihood:                -576.91
No. Observations:                  50   AIC:                             1164.
Df Residuals:                      45   BIC:                             1173.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.903e+04   1.84e+04      1.033      0.307   -1.81e+04    5.61e+04
x1         -1703.7028   9337.989     -0.182      0.856   -2.05e+04    1.71e+04
x2          3875.7625   9002.603      0.431      0.669   -1.43e+04     2.2e+04
x3             0.3239      0.133      2.426      0.019       0.055       0.593
x4             0.2507      0.031      7.997      0.000       0.188       0.314
==============================================================================
Omnibus:                        5.729   Durbin-Watson:                   1.266
Prob(Omnibus):                  0.057   Jarque-Bera (JB):                5.349
Skew:                          -0.461   Prob(JB):                       0.0689
Kurtosis:                       4.311   Cond. No.                     1.34e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.34e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [175]:
X_opt = X[:,[0,2,3,4,5]]
X_opt = X_opt.astype(np.float64)

In [176]:
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()

In [177]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Tue, 24 Oct 2023   Prob (F-statistic):           8.50e-29
Time:                        22:01:27   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.018e+04   6747.623      7.437      0.000    3.66e+04    6.38e+04
x1          -136.5042   2801.719     -0.049      0.961   -5779.456    5506.447
x2             0.8059      0.046     17.571      0.000       0.714       0.898
x3            -0.0269      0.052     -0.521      0.605      -0.131       0.077
x4             0.0271      0.017      1.625      0.111      -0.007       0.061
==============================================================================
Omnibus:                       14.892   Durbin-Watson:                   1.284
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.665
Skew:                          -0.949   Prob(JB):                     1.97e-05
Kurtosis:                       5.608   Cond. No.                     1.43e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [178]:
X_opt = X[:,[0,3,4,5]]
X_opt = X_opt.astype(np.float64)

In [179]:
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()

In [180]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Tue, 24 Oct 2023   Prob (F-statistic):           4.53e-30
Time:                        22:01:32   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [181]:
X_opt = X[:,[0,3,5]]
X_opt = X_opt.astype(np.float64)

In [182]:
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()

In [183]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 24 Oct 2023   Prob (F-statistic):           2.16e-31
Time:                        22:01:38   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Nihayetinde P > SL kalmadığından X_opt içi değerimiz aşağıdaki gibidir:

In [184]:
X_opt = X[:,[0,3,5]]

In [185]:
print(X_opt)

[[1 165349.2 471784.1]
 [1 162597.7 443898.53]
 [1 153441.51 407934.54]
 [1 144372.41 383199.62]
 [1 142107.34 366168.42]
 [1 131876.9 362861.36]
 [1 134615.46 127716.82]
 [1 130298.13 323876.68]
 [1 120542.52 311613.29]
 [1 123334.88 304981.62]
 [1 101913.08 229160.95]
 [1 100671.96 249744.55]
 [1 93863.75 249839.44]
 [1 91992.39 252664.93]
 [1 119943.24 256512.92]
 [1 114523.61 261776.23]
 [1 78013.11 264346.06]
 [1 94657.16 282574.31]
 [1 91749.16 294919.57]
 [1 86419.7 0.0]
 [1 76253.86 298664.47]
 [1 78389.47 299737.29]
 [1 73994.56 303319.26]
 [1 67532.53 304768.73]
 [1 77044.01 140574.81]
 [1 64664.71 137962.62]
 [1 75328.87 134050.07]
 [1 72107.6 353183.81]
 [1 66051.52 118148.2]
 [1 65605.48 107138.38]
 [1 61994.48 91131.24]
 [1 61136.38 88218.23]
 [1 63408.86 46085.25]
 [1 55493.95 214634.81]
 [1 46426.07 210797.67]
 [1 46014.02 205517.64]
 [1 28663.76 201126.82]
 [1 44069.95 197029.42]
 [1 20229.59 185265.1]
 [1 38558.51 174999.3]
 [1 28754.33 172795.67]
 [1 27892.92 164470.

In [186]:
X_train_opt,X_test_opt,y_train_opt,y_test_opt = train_test_split(X_opt,y,test_size=0.2,random_state=0)

In [187]:
regressor.fit(X_train_opt,y_train_opt)

LinearRegression()

In [188]:
y_pred_with_backward_elimination = regressor.predict(X_test_opt)

In [189]:
np.set_printoptions(precision=2)
print("With Backward Eliminitaion")
print(np.concatenate((y_pred_with_backward_elimination.reshape(len(y_pred_with_backward_elimination),1), y_test_opt.reshape(len(y_test_opt),1)),1))

With Backward Eliminitaion
[[102284.65 103282.38]
 [133873.92 144259.4 ]
 [134182.15 146121.95]
 [ 73701.11  77798.83]
 [180642.25 191050.39]
 [114717.25 105008.31]
 [ 68335.08  81229.06]
 [ 97433.46  97483.56]
 [114580.92 110352.25]
 [170343.32 166187.94]]


In [190]:
np.set_printoptions(precision=2)
print("Without Backward Elimination")
print(np.concatenate((y_pred_without_backward_elimination.reshape(len(y_pred_without_backward_elimination),1), y_test.reshape(len(y_test),1)),1))

Without Backward Elimination
[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
